Create recognizing-the-dhamma_geoff.md
buddhist-uni/buddhist-uni.github.io pull request #148
Opened 2023-07-25 03:08 UTC by JJM317

2023-07-25 07:45 UTC, buddhist-uni commented on _content/essays/recognizing-the-dhamma_geoff.md
> +title: "Recognizing the dhamma: a study guide"
capitalization

2023-07-25 07:45 UTC, buddhist-uni commented on _content/essays/recognizing-the-dhamma_geoff.md
> +external_url: "https://www.dhammatalks.org/Archive/Writings/Ebooks/RecognizingtheDhamma_181215.pdf"
Use the proper share url: https://www.dhammatalks.org/ebook_index.html#RecognizingTheDhamma

Also: add the pdf and epub drive_links

2023-07-25 07:45 UTC, buddhist-uni commented on _content/essays/recognizing-the-dhamma_geoff.md
> +pages: 103
This belongs in `booklets` not `essays`

2023-07-25 07:45 UTC, buddhist-uni commented on _content/essays/recognizing-the-dhamma_geoff.md
> +  - suttas
the tag is `sutta` singular, not plural

2023-07-27 06:53 UTC, buddhist-uni requested changes
Try again. 😉

2023-07-27 18:43 UTC, JJM317 commented
I capitalized the 'a' after the colon. I put the Drive links for both pdf
and epub. What's the issue?

Kindly,
~Joe

On Thu, Jul 27, 2023 at 2:53 AM The Open Buddhist University <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Try again. 😉
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/buddhist-uni/buddhist-uni.github.io/pull/148#pullrequestreview-1549124838>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7JN4IOJGDRYGFRC5AFQDF3XSIF77ANCNFSM6AAAAAA2WNL7CM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-07-27 21:52 UTC, buddhist-uni commented on _content/booklets/recognizing-the-dhamma_geoff.md
> +external_url: "https://www.dhammatalks.org/Archive/Writings/Ebooks/RecognizingtheDhamma_181215.pdf"
Please use https://www.dhammatalks.org/ebook_index.html#RecognizingTheDhamma for the external url

2023-07-27 21:52 UTC, buddhist-uni commented on _content/booklets/recognizing-the-dhamma_geoff.md
> +title: "Recognizing the Dhamma: A study guide"
Shouldn't study guide also be in title case?

2023-07-27 21:52 UTC, buddhist-uni commented on _content/booklets/recognizing-the-dhamma_geoff.md
> +drive_url: :https://drive.google.com/file/d/15S-Oj6mPsSRw004kfbeISUPm3sov4bMn/view?usp=drive_link"
this is not the right format for `drive_links`

2023-07-28 12:49 UTC, JJM317 commented
So, APA style is just the first word after a colon is capitalized. MLA and
CMS capitalize everything except prepositions. For some reason, I've had
APA in mind (minus that I missed the initial A by mistake). I'll start
making sure to follow the MLS/CMS style.
--------------------




On Thu, Jul 27, 2023 at 5:52 PM The Open Buddhist University <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In _content/booklets/recognizing-the-dhamma_geoff.md
> <https://github.com/buddhist-uni/buddhist-uni.github.io/pull/148#discussion_r1276853522>
> :
>
> > @@ -0,0 +1,15 @@
> +---
> +title: "Recognizing the Dhamma: A study guide"
> +authors:
> +  - geoff
> +external_url: "https://www.dhammatalks.org/Archive/Writings/Ebooks/RecognizingtheDhamma_181215.pdf"
>
> Please use
> https://www.dhammatalks.org/ebook_index.html#RecognizingTheDhamma for the
> external url
> ------------------------------
>
> In _content/booklets/recognizing-the-dhamma_geoff.md
> <https://github.com/buddhist-uni/buddhist-uni.github.io/pull/148#discussion_r1276853697>
> :
>
> > @@ -0,0 +1,15 @@
> +---
> +title: "Recognizing the Dhamma: A study guide"
>
> Shouldn't study guide also be in title case?
> ------------------------------
>
> In _content/booklets/recognizing-the-dhamma_geoff.md
> <https://github.com/buddhist-uni/buddhist-uni.github.io/pull/148#discussion_r1276854078>
> :
>
> > @@ -0,0 +1,15 @@
> +---
> +title: "Recognizing the Dhamma: A study guide"
> +authors:
> +  - geoff
> +external_url: "https://www.dhammatalks.org/Archive/Writings/Ebooks/RecognizingtheDhamma_181215.pdf"
> +drive_url: "https://drive.google.com/file/d/1TCvWjpFNN4fKfne6Ja-S0taRGpRNPTCu/view?usp=drive_link"
> +drive_url: :https://drive.google.com/file/d/15S-Oj6mPsSRw004kfbeISUPm3sov4bMn/view?usp=drive_link"
>
> this is not the right format for drive_links
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/buddhist-uni/buddhist-uni.github.io/pull/148#pullrequestreview-1550871604>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7JN4IIEDCF2PZ4YG5PO5RDXSLPJLANCNFSM6AAAAAA2WNL7CM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-07-28 12:51 UTC, buddhist-uni reviewed
Okay... And the drive links? And the external url?

2023-07-28 18:21 UTC, JJM317 commented
What's the problem with them? I used the pdf and epub links from Drive. The
external link is from the website - is the pdf url a problem? Should we
talk about it next Wednesday?
Kindly,
~Joe

On Fri, Jul 28, 2023 at 8:51 AM The Open Buddhist University <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Okay... And the drive links? And the external url?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/buddhist-uni/buddhist-uni.github.io/pull/148#pullrequestreview-1552057766>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7JN4IONBG44VR4I35U7VWLXSOYVVANCNFSM6AAAAAA2WNL7CM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-08-03 12:21 UTC, merged