Update 404.html
buddhist-uni/buddhist-uni.github.io pull request #165
Opened 2023-08-29 21:12 UTC by StrixV54

fixes  #150

2023-08-30 09:17 UTC, buddhist-uni reviewed
Thanks for taking an initial stab at this. Is this really what you intended it to look like?

![screenshot](https://github.com/buddhist-uni/buddhist-uni.github.io/assets/61610173/741a9e56-9da3-4ba0-9c53-afea4affa399)

2023-08-30 18:00 UTC, StrixV54 commented
Yes around something like this, I can fix it more.
Can you please tell me how do I run this, I have never used ruby. Thanks.

2023-08-31 00:05 UTC, buddhist-uni commented
Install [Node](https://nodejs.org/en/download/package-manager/), [Ruby](https://www.ruby-lang.org/en/documentation/installation/), and [Bundler](https://bundler.io/).
Then run:

```bash
git clone https://github.com/buddhist-uni/buddhist-uni.github.io.git
cd buddhist-uni.github.io
npm ci
bash scripts/install-deps.bash
bundle install
bundle exec jekyll serve -tI
```

2023-09-04 01:02 UTC, buddhist-uni requested changes
In general, care needs to be taken that text overlaid on top of an image is still legible. This can be done many ways: choosing a simple background image, adding text-shadow, blurring the background, adding a semi-transparent overlay between the two layers, etc.  Also, any design should work well at all screen widths between ~300px and ~3000px. This means loading different resolution photos at different widths and making sure the layout adapts flexibly to changing widths.

2023-09-19 18:21 UTC, StrixV54 commented on 404.html
> +    background-image: url("https://images.unsplash.com/photo-1622354688049-e1a21bcb88bc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1500&q=80");
welcome

2023-09-19 18:22 UTC, StrixV54 commented
Does it looks okay, please change the main.page-context and #main.wrapper for error then it will look good.

2023-09-21 11:54 UTC, buddhist-uni commented
I'm sorry, I don't follow what you mean... what error?  It looks much better now though, thanks! :smiley: Should I just merge this, then? Or does this still need some work?

2023-09-22 11:00 UTC, StrixV54 commented
Can you share a pic  how it looks on your side now? @buddhist-uni

2023-09-23 12:18 UTC, buddhist-uni commented
![Screenshot from 2023-09-23 18-53-15](https://github.com/buddhist-uni/buddhist-uni.github.io/assets/61610173/67c00587-efda-4e9e-bbb4-0196793798c2)

2023-09-24 19:20 UTC, StrixV54 commented
Cool, yes , just wanted to make sure it looks gud on your side too. You can merge and close this PR now.

2023-09-24 21:22 UTC, merged

2023-09-24 21:22 UTC, buddhist-uni commented
Thanks for your contribution, @StrixV54 😁